Create frontend app
limebell/9c-tx-watcher pull request #3
Opened 2022-01-11 09:59 UTC by mrbartrns

2022-01-12 05:04 UTC, limebell requested changes

2022-01-12 05:04 UTC, limebell commented on client/.gitignore
> +yarn-error.log*
This file should be merged with main `.gitignore` file.

2022-01-13 06:35 UTC, mrbartrns commented
React Script Build will automatically run env.production, NOT will be executed env.development

2022-01-14 06:46 UTC, limebell approved these changes

2022-01-14 06:46 UTC, merged